version: '3'
services:
  database:
    image: mongo:latest
    networks:
      - myProject
    ports:
      - 27017:27017
    env_file:
      - .env
  backend:
    build:
      context: ./Backend
      dockerfile: 'Dockerfile'
    ports:
      - 4000:4000
    networks:
      - myProject
  frontend:
    build:
      context: ./Frontend
      dockerfile: 'Dockerfile'
    ports:
      - 3000:3000
      - 80:80 
    networks:
      - myProject

volumes:
  database: {}

networks:
  myProject:
    driver: bridge