version: '3'
services:
  database:
    image: mongo:latest
    container_name: db_container
    restart: always
    volumes:
      - mongo_db:/data/db
    networks:
      - myProject
    env_file:
      - .env
    ports:
      - 27017:27017
  backend:
    build: ./Backend
    ports:
      - 4000:4000
    networks:
      - myProject
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://db_container:27017
      - DB_NAME=my_db
      - NAME=COLLEGE_OF_COMPUTING
    depends_on:
      - database  
  frontend:
    build:
      context: ./Frontend
      dockerfile: 'Dockerfile'
    ports:
      - 3000:3000
    networks:
      - myProject
  nginx:
    build: ./Server
    container_name: nginx
    ports:
      - 443:443
    networks:
      - myProject

volumes:
  mongo_db: {}

networks:
  myProject:
    driver: bridge